version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_instance
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_AUTH_MECHANISM: SCRAM-SHA-1
      MONGO_INITDB_DATABASE: mongodb_test
    volumes:
      - ./data:/data/db
